apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cths
  namespace: ct-webhook
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/cths/
      sourceRef:
        kind: GitRepository
        name: cths
        namespace: ct-webhook
      interval: 3m
