apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web
  namespace: ct-web
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/web/
      sourceRef:
        kind: GitRepository
        name: web
        namespace: ct-web
      interval: 3m
