apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lbms
  namespace: lb-booking
spec:
  interval: 4m
  chart:
    spec:
      chart: ./charts/dev/lbms/
      sourceRef:
        kind: GitRepository
        name: lbms
        namespace: lb-booking
      interval: 2m
