apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cpss
  namespace: cr-presence
spec:
  interval: 3m
  chart:
    spec:
      chart: ./devops/gcp/charts
      sourceRef:
        kind: GitRepository
        name: cpss
        namespace: cr-presence
      interval: 1m
