apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lats
  namespace: lb-auth
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/lats/
      sourceRef:
        kind: GitRepository
        name: lats
        namespace: lb-auth
      interval: 3m
