apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: webadmin
  namespace: lb-webadmin
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/webadmin/
      sourceRef:
        kind: GitRepository
        name: webadmin
        namespace: lb-webadmin
      interval: 3m
