apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lfms
  namespace: lb-filemanager
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/lfms/
      sourceRef:
        kind: GitRepository
        name: lfms
        namespace: lb-filemanager
      interval: 3m
