apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lams
  namespace: lb-account
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/lams/
      sourceRef:
        kind: GitRepository
        name: lams
        namespace: lb-account
      interval: 3m
