apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ctws
  namespace: ct-wallet
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/ctws/
      sourceRef:
        kind: GitRepository
        name: ctws
        namespace: ct-wallet
      interval: 3m
