apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ctps
  namespace: ct-project
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/ctps/
      sourceRef:
        kind: GitRepository
        name: ctps
        namespace: ct-project
      interval: 3m
