apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ctas
  namespace: ct-account
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/ctas/
      sourceRef:
        kind: GitRepository
        name: ctas
        namespace: ct-account
      interval: 3m
