apiVersion: v1
kind: Secret
metadata:
  name: slack-url
  namespace: ct-account
type: Opaque
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDdRUVI5RVFLL0IwMktZRUQxN0QyL05aR2hoR25DUFhLWEtZczk5ejI3QXp6UAo=
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack
  namespace: ct-account
spec:
  type: slack
  channel: ct-actions
  secretRef:
    name: slack-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  generation: 2
  name: slack-alerts
  namespace: ct-account
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: HelmRelease
      name: '*'
    - kind: HelmChart
      name: '*'
