apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ccms
  namespace: cr-company
spec:
  interval: 3m
  chart:
    spec:
      chart: ./devops/gcp/charts
      sourceRef:
        kind: GitRepository
        name: ccms
        namespace: cr-company
      interval: 1m
