apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lsss
  namespace: lb-storesearch
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/dev/lsss/
      sourceRef:
        kind: GitRepository
        name: lsss
      interval: 3m
